-- =============================================================================
-- CAMINO · CONTENIDO INICIAL DE EJEMPLO (no es contenido pastoral definitivo)
-- Módulos de las 6 etapas, 2 planes, 1 reto semanal. Idempotente: puede
-- ejecutarse varias veces. Las citas bíblicas son citas breves aproximadas; verifícalas
-- con la versión con licencia que use tu organización antes de publicar.
-- Aplicar:  psql "$DATABASE_URL" -f supabase/content/001_starter_content.sql
--           (o pegarlo en el SQL Editor de Supabase)
-- =============================================================================
begin;

insert into public.devotionals (id, title, minutes, scripture_ref, scripture_text, scripture_version, reflection, question, prayer, action, is_published) values
  ('5a82d2b6-418f-5f3d-84c4-fbb30b494de6', '¿Quién es Jesús?', 5, 'Juan 14:6', 'Jesús dijo: Yo soy el camino, la verdad y la vida.', null, 'Antes de hablar de reglas o de religión, Jesús se presenta a sí mismo como un camino. No un examen que aprobar, sino alguien con quien caminar. Conocerlo es una relación que empieza hoy, tal como eres.', 'Si Jesús es un camino, ¿qué te gustaría preguntarle hoy?', 'Jesús, quiero conocerte de verdad, no solo saber cosas de ti. Muéstrame quién eres y camina conmigo.', 'Escribe en una frase quién es Jesús para ti hoy. Sin respuestas correctas.', true),
  ('8f4225c6-53b9-5781-ae65-453c68a1c964', 'Gracia que no se gana', 5, 'Efesios 2:8–9', 'Por gracia ustedes han sido salvados mediante la fe; no es por obras, es un regalo de Dios.', null, 'Vivimos rodeados de méritos: notas, likes, logros. La gracia rompe esa lógica. Dios no te ama porque rindes; te ama porque es amor. Lo que haces nace de ese amor, no lo compra.', '¿En qué área sientes que tienes que ganarte el cariño de Dios?', 'Padre, gracias porque tu amor no depende de mi desempeño. Ayúdame a recibirlo como un regalo.', 'Haz hoy algo bueno por alguien sin esperar nada a cambio.', true),
  ('372d2917-5af4-50a2-9902-a7cf53132b38', 'Tu primer paso', 5, 'Lucas 15:20', 'Cuando todavía estaba lejos, su padre lo vio, corrió hacia él, lo abrazó y lo besó.', null, 'El hijo apenas dio unos pasos y el padre corrió el resto del camino. Así es Dios contigo: no espera que llegues perfecto. Basta con volverte hacia Él.', '¿Cuál sería un pequeño paso hacia Dios esta semana?', 'Dios, aquí estoy. No traigo todo resuelto, pero quiero volver a ti. Gracias por correr hacia mí.', 'Elige un momento fijo de 5 minutos mañana para hablar con Dios.', true),
  ('a3e690ba-aedd-5bc5-8bca-58d6b0dc2f98', 'Cómo leer la Biblia', 5, 'Salmo 119:105', 'Tu palabra es una lámpara a mis pies y una luz en mi camino.', null, 'La Biblia no es un libro para leer de corrido sin entender. Empieza por un evangelio, lee pocos versículos, pregunta: ¿qué dice?, ¿qué me dice?, ¿qué haré? Una lámpara alumbra el siguiente paso, no todo el camino.', '¿Qué te cuesta más al leer la Biblia?', 'Señor, abre mi entendimiento. Que tu Palabra sea luz para mi siguiente paso.', 'Lee hoy Marcos 1:1–20 y subraya una frase que te llame la atención.', true),
  ('9adb2689-6114-5740-a1fc-34cf265168e6', 'Cómo orar', 5, 'Mateo 6:6', 'Cuando ores, entra en tu cuarto, cierra la puerta y ora a tu Padre, que está en lo secreto.', null, 'Orar no requiere palabras perfectas. Es hablar con Dios con honestidad: agradecer, contarle lo que pasa, pedir, escuchar. Un lugar tranquilo y un poco de constancia hacen una gran diferencia.', '¿Qué te gustaría contarle a Dios hoy?', 'Padre, enséñame a orar. Quiero hablarte como se habla con alguien que me ama.', 'Ora 3 minutos hoy usando: gracias, perdón, ayúdame.', true),
  ('8acac1c4-1f88-5e6e-a1c6-ec1e6d3b7c6d', 'Escuchar a Dios', 5, '1 Samuel 3:10', 'Samuel respondió: Habla, que tu siervo escucha.', null, 'Muchas veces oramos hablando todo el tiempo. Escuchar es aprender a hacer silencio, leer la Palabra con calma y prestar atención a lo que Dios va poniendo en tu corazón, en tu comunidad y en tus circunstancias.', '¿Cuándo fue la última vez que hiciste silencio para escuchar?', 'Habla, Señor, que te escucho. Calma mi mente y afina mi corazón a tu voz.', 'Pasa 5 minutos en silencio hoy, sin pantalla, con un versículo.', true),
  ('9b397806-5f67-52da-9e7c-0b94ba7e5acb', 'Identidad', 5, 'Efesios 2:10', 'Somos hechura de Dios, creados en Cristo Jesús para buenas obras.', null, 'Tu valor no lo define tu apariencia, tus seguidores ni tus errores. Dios te hizo con intención. Saberlo cambia cómo te ves y cómo tratas a los demás.', '¿Qué voces suelen definir quién eres?', 'Dios, gracias porque soy obra tuya. Ayúdame a creer lo que dices de mí.', 'Escribe tres verdades que Dios dice de ti y ponlas donde las veas.', true),
  ('cb3c4a50-8523-5ee9-906e-a644ef51326b', 'Fe en lo cotidiano', 5, 'Colosenses 3:17', 'Todo lo que hagan, de palabra o de obra, háganlo en el nombre del Señor Jesús.', null, 'La fe no se queda en el domingo. Se vive en la escuela, en casa, en el trabajo, en cómo hablas y cómo usas tu tiempo. Cada día ordinario es un lugar para encontrarte con Dios.', '¿En qué parte de tu día te cuesta más vivir tu fe?', 'Señor, quiero que te notes en mi día común. Acompáñame en lo pequeño.', 'Ofrece a Dios una tarea aburrida de hoy y hazla con excelencia.', true),
  ('ce5e8939-af88-5b29-83ff-e944303e40c7', 'Amar a tu prójimo', 5, 'Lucas 10:27', 'Ama al Señor tu Dios con todo tu corazón… y a tu prójimo como a ti mismo.', null, 'Amar a Dios y amar a las personas van juntos. El prójimo es quien tienes cerca, incluso quien no te cae bien. El amor se nota en gestos concretos.', '¿A quién te está costando amar últimamente?', 'Dios, dame un corazón como el tuyo para ver y servir a las personas.', 'Escribe un mensaje amable a alguien con quien tengas distancia.', true),
  ('63fcdaa6-92ea-5249-bdfe-3acae694c039', 'Dones para servir', 5, '1 Pedro 4:10', 'Cada uno ponga al servicio de los demás el don que haya recibido.', null, 'Todos tenemos algo que aportar: habilidades, tiempo, sensibilidad. Servir no es para unos pocos; es parte de seguir a Jesús. Descubrir cómo sirves es un proceso, no un examen.', '¿Qué cosas haces con gusto que podrían ayudar a otros?', 'Señor, muéstrame cómo puedo servir con lo que me diste.', 'Pregunta a tu líder dónde se necesita ayuda esta semana.', true),
  ('c17a6f12-26a1-550c-b5bb-df427e2c5282', 'Servir con alegría', 5, 'Marcos 10:45', 'El Hijo del hombre no vino para que le sirvan, sino para servir.', null, 'Jesús lavó pies y se acercó a quienes nadie veía. Servir con alegría nace de saberte amado, no de buscar reconocimiento.', '¿Qué te motiva cuando sirves?', 'Jesús, quiero servir como tú: con humildad y con gozo.', 'Haz hoy un servicio que nadie vaya a notar.', true),
  ('81347af8-7ee8-5c89-8ef4-f79973b37be8', 'Tu historia importa', 5, '1 Pedro 3:15', 'Estén siempre preparados para responder a todo el que les pida razón de la esperanza que hay en ustedes.', null, 'Compartir tu fe empieza por contar lo que Dios ha hecho en ti. No necesitas tener todas las respuestas, solo honestidad y respeto.', '¿Cómo contarías en tres frases lo que Dios ha hecho en tu vida?', 'Dios, dame valor y amabilidad para compartir mi esperanza.', 'Escribe tu historia en tres frases.', true),
  ('e5cd158e-d0a4-5e9e-b69f-99c81e3604b8', 'Ser luz', 5, 'Mateo 5:14–16', 'Ustedes son la luz del mundo… que su luz brille delante de todos.', null, 'La luz no hace ruido, simplemente alumbra. Tu forma de tratar a otros puede abrir conversaciones sobre Jesús de manera natural.', '¿Dónde crees que Dios quiere que brilles hoy?', 'Señor, que mi vida apunte a ti con sencillez.', 'Invita a alguien a una actividad de tu grupo de jóvenes.', true),
  ('24c07a4b-401f-5271-8958-c09a9160afdf', 'Acompañar a otros', 5, '2 Timoteo 2:2', 'Lo que me has oído decir… encomiéndalo a creyentes dignos de confianza, que a su vez estén capacitados para enseñar a otros.', null, 'Crecer también es ayudar a otros a crecer. Acompañar no es controlar: es escuchar, orar y caminar junto a alguien con paciencia.', '¿Quién te ha acompañado a ti en tu fe?', 'Señor, hazme alguien que acompaña con paciencia y respeto.', 'Agradece hoy a una persona que te haya acompañado.', true),
  ('0e575d00-d5f8-5dc2-8ef9-da23bedc776a', 'Liderar sirviendo', 5, 'Juan 13:14–15', 'Si yo, el Señor y el Maestro, les he lavado los pies, también ustedes deben lavarse los pies los unos a los otros.', null, 'El liderazgo en el Reino se parece a una toalla, no a un trono. Guiar a otros es servirlos y señalarles a Jesús.', '¿Qué significa para ti liderar como Jesús?', 'Jesús, enséñame a liderar desde el servicio.', 'Pregunta a alguien de tu grupo cómo puedes orar por él o ella.', true),
  ('35ae7b6f-0e8e-50eb-a359-ab3ab49915ea', 'Empezar pequeño', 6, 'Lamentaciones 3:22–23', 'Sus misericordias son nuevas cada mañana; ¡grande es su fidelidad!', null, 'La constancia no empieza con horas de oración, sino con pasos pequeños y repetibles. Dios te recibe nuevo cada mañana.', '¿Qué paso pequeño podrías repetir cada día?', 'Señor, gracias porque cada día es una nueva oportunidad contigo.', 'Elige una hora fija para tu devocional esta semana.', true),
  ('2ca78ed9-69dd-5aa5-8306-d18bf54f5cf5', 'Un lugar, una hora', 6, 'Marcos 1:35', 'Muy de madrugada, Jesús se levantó, salió y se fue a un lugar solitario, donde se puso a orar.', null, 'Jesús tenía un lugar y un momento. Los hábitos crecen mejor cuando tienen un espacio claro en tu día.', '¿Dónde y cuándo puedes encontrarte con Dios sin distracciones?', 'Jesús, enséñame a apartar tiempo para ti como tú lo hacías con el Padre.', 'Prepara tu lugar: Biblia, cuaderno y el celular en silencio.', true),
  ('1574465f-29a2-5e19-86d9-733e0fe36160', 'Cuando no tengo ganas', 6, 'Gálatas 6:9', 'No nos cansemos de hacer el bien, porque a su debido tiempo cosecharemos.', null, 'Habrá días sin ganas. La constancia no depende de sentir, sino de volver. Dios honra los pasos pequeños dados con fidelidad.', '¿Qué haces normalmente cuando no tienes ganas?', 'Señor, cuando me falten ganas, dame fidelidad para volver a ti.', 'Hoy lee solo un versículo y ora un minuto. Eso cuenta.', true),
  ('453825a2-96d2-5fc9-bc22-332948864615', 'Cuando Dios parece guardar silencio', 6, 'Salmo 13:1–2, 5', '¿Hasta cuándo, Señor? ¿Me olvidarás para siempre? … Pero yo confío en tu gran amor.', null, 'David se atrevió a decirle a Dios cómo se sentía, y aun así eligió confiar. El silencio de Dios no es ausencia; es una invitación a seguir hablándole.', '¿Hay algo por lo que llevas tiempo orando?', 'Señor, aunque no entienda tus tiempos, elijo confiar. Enséñame a esperarte sin dejar de hablarte…', 'Dedica hoy 5 minutos a hablar con Dios sin pedirle nada.', true),
  ('eadf3c79-1142-5a3b-a4a3-7644c3dda56f', 'Volver sin culpa', 6, '1 Juan 1:9', 'Si confesamos nuestros pecados, Dios, que es fiel y justo, nos los perdonará.', null, 'Fallar un día no borra tu camino. La gracia te invita a volver sin castigarte. Siempre puedes volver.', '¿Qué te hace sentir que ya no puedes volver?', 'Padre, gracias porque siempre puedo volver a ti. Recibo tu perdón.', 'Si te saltaste días, retoma hoy sin culpa.', true),
  ('67786f07-59fc-54e4-849b-34622d595b6a', 'Pequeñas raíces', 6, 'Salmo 1:3', 'Es como el árbol plantado a la orilla de un río que, cuando llega su tiempo, da fruto.', null, 'Las raíces crecen sin que se vean. Cada día que apartas tiempo con Dios fortalece algo profundo en ti.', '¿Qué fruto te gustaría ver en tu vida?', 'Señor, planta mis raíces en ti para que dé fruto a su tiempo.', 'Comparte con alguien de confianza un hábito que estás construyendo.', true),
  ('bfa2b868-1e9c-566e-834b-9191a052eff5', 'Un camino, no una competencia', 6, 'Hebreos 12:1–2', 'Corramos con perseverancia la carrera que tenemos por delante, fijando la mirada en Jesús.', null, 'No compites con nadie. Tu camino es tuyo y Jesús va contigo. Mira cuánto has recorrido esta semana.', '¿Qué aprendiste de ti en estos siete días?', 'Jesús, gracias por caminar conmigo. Quiero seguir, a mi ritmo, contigo.', 'Decide cómo seguirás tu rutina la próxima semana.', true),
  ('8ae581f5-d6be-5938-bbd2-bab007cfe740', 'No estás solo en esto', 6, 'Filipenses 4:6–7', 'No se inquieten por nada; más bien, en toda ocasión, presenten sus peticiones a Dios… y la paz de Dios cuidará sus corazones.', null, 'La ansiedad suele hacernos sentir solos. Dios te invita a llevarle todo, también lo que parece pequeño. Su paz cuida tu corazón.', '¿Qué te está quitando la paz hoy?', 'Dios, te entrego lo que me preocupa. Cuida mi corazón con tu paz.', 'Escribe tus preocupaciones y ora por cada una.', true),
  ('74337ad2-6aa5-56c1-ba73-f7d061de09e5', 'Nombrar lo que sientes', 6, 'Salmo 42:5', '¿Por qué voy a inquietarme? ¿Por qué me voy a angustiar? En Dios pondré mi esperanza.', null, 'El salmista habla con su propia alma. Ponerle nombre a lo que sientes no es falta de fe; es honestidad delante de Dios.', 'Si tuvieras que nombrar lo que sientes, ¿qué palabra usarías?', 'Señor, esto es lo que siento. Gracias porque puedo ser honesto contigo.', 'Habla con alguien de confianza sobre cómo te sientes.', true),
  ('2ee8b14f-08b5-5018-bf61-c3cb1d428fdb', 'Un día a la vez', 6, 'Mateo 6:34', 'No se angustien por el mañana, el cual tendrá sus propios afanes.', null, 'Jesús no minimiza el futuro, pero te invita a vivir el hoy con Él. Un día a la vez es suficiente.', '¿Qué parte del mañana intentas cargar hoy?', 'Jesús, ayúdame a vivir este día contigo y a soltar el mañana.', 'Antes de dormir, agradece tres cosas de hoy.', true),
  ('8a2433ab-3adc-529d-9aaf-45c70ea99561', 'Echa tu ansiedad', 6, '1 Pedro 5:7', 'Depositen en él toda ansiedad, porque él cuida de ustedes.', null, 'Echar es un verbo activo: soltar algo pesado sobre alguien más fuerte. Dios cuida de ti de verdad.', '¿Qué ansiedad necesitas soltar hoy?', 'Padre, suelto esto en tus manos. Gracias porque cuidas de mí.', 'Respira despacio un minuto repitiendo: Él cuida de mí.', true),
  ('8e264380-3754-5557-a745-91ee32f15c42', 'Paz que no entiendo', 6, 'Juan 14:27', 'La paz les dejo; mi paz les doy… No se angustien ni se acobarden.', null, 'La paz de Jesús no depende de que todo esté resuelto. Es su presencia en medio de lo que no controlas.', '¿Dónde necesitas la paz de Jesús esta semana?', 'Jesús, recibo tu paz. Quédate conmigo en lo que no puedo controlar.', 'Desconéctate de redes una hora y descansa.', true),
  ('c367e74d-3ded-5922-9943-2a710d5528d6', 'Cuando la mente no para', 6, 'Isaías 26:3', 'Al de firme propósito guardarás en perfecta paz, porque en ti confía.', null, 'Cuando los pensamientos corren, fijar la mente en Dios es un ejercicio diario. Puedes entrenar tu atención con su Palabra.', '¿Qué pensamiento se repite más en tu mente?', 'Dios, ordena mis pensamientos y guárdame en tu paz.', 'Memoriza Isaías 26:3.', true),
  ('d473dcd1-13f6-544e-890e-26cca65bc587', 'Confiar de nuevo', 6, 'Proverbios 3:5–6', 'Confía en el Señor de todo corazón… y él allanará tus sendas.', null, 'Confiar es una decisión que se renueva. No tienes que entenderlo todo para dar el siguiente paso con Dios.', '¿En qué área quieres confiar de nuevo en Dios?', 'Señor, elijo confiar en ti. Guía mis pasos.', 'Pide a alguien de tu grupo que ore por ti esta semana.', true)
on conflict (id) do nothing;

insert into public.plans (id, title, summary, category, color, minutes_per_day, recommended_stage_id, growth_areas, is_published)
values ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 'Construyendo constancia', 'Siete días para crear un hábito sencillo de tiempo con Dios, sin presión y con gracia.', 'foundations', '#35D07F', 6, (select id from public.journey_stages where key = 'crece'), '{consistency,prayer,bible}', true)
on conflict (id) do nothing;

insert into public.plan_days (plan_id, day_number, devotional_id) values
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 1, '35ae7b6f-0e8e-50eb-a359-ab3ab49915ea'),
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 2, '2ca78ed9-69dd-5aa5-8306-d18bf54f5cf5'),
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 3, '1574465f-29a2-5e19-86d9-733e0fe36160'),
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 4, '453825a2-96d2-5fc9-bc22-332948864615'),
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 5, 'eadf3c79-1142-5a3b-a4a3-7644c3dda56f'),
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 6, '67786f07-59fc-54e4-849b-34622d595b6a'),
  ('a42e17c0-eef6-54b7-8634-d35973a23b9c', 7, 'bfa2b868-1e9c-566e-834b-9191a052eff5')
on conflict (plan_id, day_number) do nothing;

insert into public.plans (id, title, summary, category, color, minutes_per_day, recommended_stage_id, growth_areas, is_published)
values ('84f2b14d-7061-5a91-a195-138df653f2fb', 'Ansiedad y confianza', 'Siete días para aprender a entregarle a Dios lo que te quita la paz.', 'daily_life', '#9B6BFF', 6, (select id from public.journey_stages where key = 'crece'), '{identity,prayer,relationships}', true)
on conflict (id) do nothing;

insert into public.plan_days (plan_id, day_number, devotional_id) values
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 1, '8ae581f5-d6be-5938-bbd2-bab007cfe740'),
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 2, '74337ad2-6aa5-56c1-ba73-f7d061de09e5'),
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 3, '2ee8b14f-08b5-5018-bf61-c3cb1d428fdb'),
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 4, '8a2433ab-3adc-529d-9aaf-45c70ea99561'),
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 5, '8e264380-3754-5557-a745-91ee32f15c42'),
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 6, 'c367e74d-3ded-5922-9943-2a710d5528d6'),
  ('84f2b14d-7061-5a91-a195-138df653f2fb', 7, 'd473dcd1-13f6-544e-890e-26cca65bc587')
on conflict (plan_id, day_number) do nothing;

insert into public.journey_modules (id, stage_id, position, title, kind, devotional_id, plan_id) values
  ('e13910f3-3240-5caf-856c-9155494a0da2', (select id from public.journey_stages where key = 'encuentra'), 1, '¿Quién es Jesús?', 'devotional', '5a82d2b6-418f-5f3d-84c4-fbb30b494de6', null),
  ('d7c61ab1-96f1-53b4-902f-9447c4054023', (select id from public.journey_stages where key = 'encuentra'), 2, 'Gracia que no se gana', 'devotional', '8f4225c6-53b9-5781-ae65-453c68a1c964', null),
  ('817fba7c-ab26-57ca-ac3e-405d7629b948', (select id from public.journey_stages where key = 'encuentra'), 3, 'Tu primer paso', 'devotional', '372d2917-5af4-50a2-9902-a7cf53132b38', null),
  ('f9bf9617-ad9b-5e7e-ba50-cb07fd3596c8', (select id from public.journey_stages where key = 'crece'), 1, 'Cómo leer la Biblia', 'devotional', 'a3e690ba-aedd-5bc5-8bca-58d6b0dc2f98', null),
  ('4f3eddb4-ea96-53db-9393-b7ca880c7cbe', (select id from public.journey_stages where key = 'crece'), 2, 'Cómo orar', 'devotional', '9adb2689-6114-5740-a1fc-34cf265168e6', null),
  ('b2bba1d0-a2cd-5fa7-8261-7d0ca5e2b4aa', (select id from public.journey_stages where key = 'crece'), 3, 'Construyendo constancia', 'plan', null, 'a42e17c0-eef6-54b7-8634-d35973a23b9c'),
  ('db03f598-36de-5d65-b16e-63306e38a259', (select id from public.journey_stages where key = 'crece'), 4, 'Escuchar a Dios', 'devotional', '8acac1c4-1f88-5e6e-a1c6-ec1e6d3b7c6d', null),
  ('8e9b3c10-f8b1-50b3-9b38-b16174812043', (select id from public.journey_stages where key = 'crece'), 5, 'Identidad', 'devotional', '9b397806-5f67-52da-9e7c-0b94ba7e5acb', null),
  ('85b6ae5c-9d82-52df-a721-abee14b3bed4', (select id from public.journey_stages where key = 'vive'), 1, 'Fe en lo cotidiano', 'devotional', 'cb3c4a50-8523-5ee9-906e-a644ef51326b', null),
  ('e95d69a5-59a4-518e-816c-816bac103a6c', (select id from public.journey_stages where key = 'vive'), 2, 'Amar a tu prójimo', 'devotional', 'ce5e8939-af88-5b29-83ff-e944303e40c7', null),
  ('4189b475-0495-50cf-8685-e481e0815c49', (select id from public.journey_stages where key = 'sirve'), 1, 'Dones para servir', 'devotional', '63fcdaa6-92ea-5249-bdfe-3acae694c039', null),
  ('7fa724f0-4f93-58c8-8c42-1c16bb4b1c91', (select id from public.journey_stages where key = 'sirve'), 2, 'Servir con alegría', 'devotional', 'c17a6f12-26a1-550c-b5bb-df427e2c5282', null),
  ('0531c0ec-8387-5f6c-ba17-f46caeb44ac9', (select id from public.journey_stages where key = 'comparte'), 1, 'Tu historia importa', 'devotional', '81347af8-7ee8-5c89-8ef4-f79973b37be8', null),
  ('da40c179-b2d3-5295-80fc-ec9aac863a92', (select id from public.journey_stages where key = 'comparte'), 2, 'Ser luz', 'devotional', 'e5cd158e-d0a4-5e9e-b69f-99c81e3604b8', null),
  ('4e88129b-4ea4-5ad1-aa02-6371163e756a', (select id from public.journey_stages where key = 'guia'), 1, 'Acompañar a otros', 'devotional', '24c07a4b-401f-5271-8958-c09a9160afdf', null),
  ('ca43d3fc-8422-5288-b86e-528d7d30b90a', (select id from public.journey_stages where key = 'guia'), 2, 'Liderar sirviendo', 'devotional', '0e575d00-d5f8-5dc2-8ef9-da23bedc776a', null)
on conflict (id) do nothing;

insert into public.challenges (id, title, description, kind, days_target, stage_id, is_published)
values ('7907068f-a753-5015-b9df-070e79167f00', 'Ora por un amigo', 'Elige a alguien que no conoce a Jesús. Ora por esa persona 5 días esta semana.', 'weekly', 5, (select id from public.journey_stages where key = 'vive'), true)
on conflict (id) do nothing;

commit;
