/**
 * Writes out/sw.js after `next build` (static export).
 *
 * Strategy (docs/pwa.md):
 *  - Precache the app shell: HTML of every exported route, JS/CSS/fonts in _next/static, icons, manifest.
 *  - Navigations: network-first → cached page → /offline/.
 *  - Hashed static assets: cache-first (immutable).
 *  - Cross-origin requests (Supabase API, auth, storage) are NEVER intercepted or cached:
 *    private user data must not end up in the Cache Storage without an explicit strategy.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const outDir = join(root, "out");

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(outDir).map((f) => "/" + relative(outDir, f).split(sep).join("/"));

const precache = files
  .filter((f) => f !== "/sw.js")
  .filter(
    (f) =>
      f.startsWith("/_next/static/") ||
      f.startsWith("/icons/") ||
      f === "/manifest.webmanifest" ||
      f.endsWith("/index.html") ||
      f === "/404.html",
  )
  // Leader/admin panels are online-only and not part of the offline shell.
  .filter((f) => !/^\/(leader|admin)\//.test(f))
  .map((f) => (f.endsWith("/index.html") ? f.slice(0, -"index.html".length) : f))
  .sort();

const hash = createHash("sha256");
for (const f of precache) {
  const path = f.endsWith("/") ? join(outDir, f, "index.html") : join(outDir, f);
  hash.update(f).update(readFileSync(path));
}
const version = hash.digest("hex").slice(0, 12);

const sw = `/* Camino service worker · generated by scripts/generate-sw.mjs · do not edit */
const VERSION = ${JSON.stringify(version)};
const SHELL_CACHE = "camino-shell-" + VERSION;
const RUNTIME_CACHE = "camino-runtime-" + VERSION;
const PRECACHE = ${JSON.stringify(precache)};
const OFFLINE_URL = "/offline/";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("camino-") && !k.endsWith(VERSION)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

function normalizePage(url) {
  let path = url.pathname;
  if (!path.endsWith("/") && !path.includes(".")) path += "/";
  return path;
}

async function networkFirstPage(request) {
  const url = new URL(request.url);
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(RUNTIME_CACHE);
      cache.put(normalizePage(url), response.clone());
    }
    return response;
  } catch {
    const cached = (await caches.match(normalizePage(url))) || (await caches.match(OFFLINE_URL));
    return cached || Response.error();
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) (await caches.open(RUNTIME_CACHE)).put(request, response.clone());
  return response;
}

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) (await caches.open(RUNTIME_CACHE)).put(request, response.clone());
    return response;
  } catch {
    return (await caches.match(request)) || Response.error();
  }
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // never touch Supabase or third parties
  if (url.pathname.startsWith("/leader") || url.pathname.startsWith("/admin")) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirstPage(request));
  } else if (url.pathname.startsWith("/_next/static/") || url.pathname.startsWith("/icons/")) {
    event.respondWith(cacheFirst(request));
  } else {
    event.respondWith(networkFirst(request));
  }
});

self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});
`;

writeFileSync(join(outDir, "sw.js"), sw);
console.log(`sw.js written · version ${version} · ${precache.length} precached entries`);
